---
title: "Afternoon Exercise"
author: "Melinda Higgins"
date: "7/30/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# set up knitr options
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

# load libraries needed for this document
library(dplyr)
library(Hmisc)
library(readr)

# load the abalone modified dataset
load("abaloneMod.RData")
```

## Figure 1 - Association between Age and Whole Weight

```{r}
ggplot(data = abaloneMod,
       aes(x=wholeWeight, y=age)) +
  geom_point(aes(color=sex)) +
  geom_smooth(color="red", method=lm) +
  facet_wrap(~sex) +
  ggtitle("Age by Whole Weight and by Sex with Linear Fit Lines")
```

Interesting to see that the slope is steepest (stronger correlation) for the infants.

## Model 1

```{r}
lm1 <- lm(age ~ wholeWeight, data = abaloneMod)
slm1 <- summary(lm1)
slm1

# make prettier table
library(knitr)
knitr::kable(slm1$coefficients,
             caption = "Model 1 Age by Whole Weight")
```

## Test for interaction by sex

```{r}
lm2 <- lm(age ~ wholeWeight + as.factor(sex), 
          data = abaloneMod)
slm2 <- summary(lm2)
slm2

# make prettier table
knitr::kable(slm2$coefficients,
             caption = "Model 2 Age by Whole Weight and sex")
```


```{r}
lm3 <- lm(age ~ wholeWeight + as.factor(sex) + 
            wholeWeight * as.factor(sex), 
          data = abaloneMod)
slm3 <- summary(lm3)
slm3
```

